# Generated by Django 3.1.6 on 2021-03-09 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('currency_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('currency_ccy', models.CharField(max_length=3)),
                ('currency_base_ccy', models.CharField(max_length=3)),
                ('buy', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trend_buy', models.CharField(max_length=2)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trend_sale', models.CharField(max_length=2)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
